name: Google Cloud Run Deployment

on:
  push:
    branches: [master]



env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west1
  SERVICE_NAME: kontrakt-api
  DATABASE_URL: ${{ secrets.RUN_SA_KEY }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
      - uses: docker/build-push-action@v1
        with:
          repository: eu.gcr.io/kontrakt-273811/kontrakt-api:latest
      # Build and push image to Google Container Registry
#      - name: Build
#        run:
##        run: |-
##          gcloud builds submit \
##            --quiet \
##            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
##            --substitutions=DATABASE_URL=$DATABASE_URL
#      # Deploy image to Cloud Run
#      - name: Deploy
#        run: |-
#          gcloud run deploy "$SERVICE_NAME" \
#            --quiet \
#            --region "$RUN_REGION" \
#            --image "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
#            --platform "managed" \
#            --allow-unauthenticated
